### ISSUE TITLE
Cropselect for Kirby 3

### ISSUE THREAD

**Issue by medienbaecker** [jenstornell/kirby-plugins#586]
**Url:** https://github.com/medienbaecker/kirby-cropselect

### Information

This is a visual crop selector for Kirby 3. You can select from 9 different crop positions and use it like that:

### Blueprint:
```yaml
fields:
    cropselect:
        label:  Select crop position
        type:   cropselect
```

### Template:
```php
$image->crop(100, 200, $image->cropselect());
```

### Screenshot

![Preview](https://user-images.githubusercontent.com/7975568/43335873-3fba4ad8-91d0-11e8-8604-0755b2655a58.gif)
